title: Soham Sangole # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br>Passionate second-year IT student with a love for Machine Learning. Always tinkering and experimenting with new technologies on GitHub.<br>
  <br><br>
  <a href="https://www.linkedin.com/in/sohamsangole/">View My LinkedIn Profile</a> 
  <a href="pdf/Resume.pdf">Resume</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
